[package]
name = "tweet-provider"
version = "0.1.0"
authors = ["Rasmus Karlsson <rasmus.karlsson@pajlada.com>", "Lucas Desgouilles <ldesgoui@ldesgoui.xyz>"]
edition = "2018"

[dependencies]
anyhow = "1"
async-tungstenite = { version = "0.3",  features = ["tokio-runtime"] }
futures = "0.3"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
simple_logger = "1.4"
structopt = "0.3"
thiserror = "1"
tokio = { version = "0.2", features = ["full"] }
toml = "0.5"

[dependencies.egg-mode]
git = "https://github.com/QuietMisdreavus/twitter-rs"
default-features = false
features = ["hyper-rustls"]
