[package]
name = "tweet-provider"
description = "Provides a WebSocket interface for pajbot1 to reduce Twitter API usage"
version = "0.1.2"
authors = ["Rasmus Karlsson <rasmus.karlsson@pajlada.com>", "Lucas Desgouilles <ldesgoui@ldesgoui.xyz>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/pajbot/tweet-provider"
keywords = ["pajbot", "twitter"]
categories = ["twitter", "application"]

[dependencies]
anyhow = "1.0.71"
async-stream = "0.3.5"
async-tungstenite = { version = "0.22.2",  features = ["tokio-runtime"] }
egg-mode = { version = "0.16.1", default-features = false, features = ["rustls"] }
futures = "0.3.28"
log = "0.4.19"
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0.100"
simple_logger = "4.2.0"
clap = { version = "4.3.11", features = ["derive", "env"]}
thiserror = "1.0.43"
tokio = { version = "1.29.1", features = ["full"] }
toml = "0.7.6"

[dev-dependencies]
rstest = { version = "0.18.1", default-features = false }
trycmd = "0.14.16"
