[package]
name = "tweet-provider"
description = "Provides a WebSocket interface for pajbot1 to reduce Twitter API usage"
version = "0.1.2"
authors = ["Rasmus Karlsson <rasmus.karlsson@pajlada.com>", "Lucas Desgouilles <ldesgoui@ldesgoui.xyz>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/pajbot/tweet-provider"
keywords = ["pajbot", "twitter"]
categories = ["twitter", "application"]

[dependencies]
anyhow = "1.0.68"
async-stream = "0.3.3"
async-tungstenite = { version = "0.19.0",  features = ["tokio-runtime"] }
egg-mode = { version = "0.16.0", default-features = false, features = ["rustls"] }
futures = "0.3.25"
log = "0.4.17"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
simple_logger = "4.0.0"
clap = { version = "4.1.1", features = ["derive", "env"]}
thiserror = "1.0.38"
tokio = { version = "1.24.2", features = ["full"] }
toml = "0.5.11"

[dev-dependencies]
trycmd = "0.14.10"
