[package]
name = "tweet-provider"
description = "Provides a WebSocket interface for pajbot1 to reduce Twitter API usage"
version = "0.1.2"
authors = ["Rasmus Karlsson <rasmus.karlsson@pajlada.com>", "Lucas Desgouilles <ldesgoui@ldesgoui.xyz>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/pajbot/tweet-provider"

[dependencies]
anyhow = "1"
async-stream = "0.3"
async-tungstenite = { version = "0.17",  features = ["tokio-runtime"] }
egg-mode = { version = "0.16", default-features = false, features = ["rustls"] }
futures = "0.3"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
simple_logger = "2.3"
clap = { version = "3", features = ["derive", "env"]}
thiserror = "1"
tokio = { version = "1.21", features = ["full"] }
toml = "0.5"

[dev-dependencies]
trycmd = "*"
