[package]
name = "tweet-provider"
version = "0.1.2"
authors = ["Rasmus Karlsson <rasmus.karlsson@pajlada.com>", "Lucas Desgouilles <ldesgoui@ldesgoui.xyz>"]
edition = "2018"

[dependencies]
anyhow = "1"
async-stream = "0.3"
async-tungstenite = { version = "0.17",  features = ["tokio-runtime"] }
egg-mode = { version = "0.16", default-features = false, features = ["rustls"] }
futures = "0.3"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
simple_logger = "2.3"
structopt = "0.3"
thiserror = "1"
tokio = { version = "1.20", features = ["full"] }
toml = "0.5"
