[websocket]
# listen_addr = "127.0.0.1:2356"

[twitter]
# consumer_key = ""
# consumer_secret = ""
# access_token = ""
# access_token_secret = ""
## list of twitter user IDs to follow by default
# default_follows = []
# follows_cache = "cache.json"
